apiVersion: v1
kind: ConfigMap
metadata:
  name: lucky-frpc-config
  namespace: lucky
data:
  frpc.toml: |
    serverAddr = "123.60.74.153"
    serverPort = 45217
    loginFailExit = false

    auth.method = "token"
    auth.additionalScopes = ["HeartBeats", "NewWorkConns"]
    auth.tokenSource.type = "file"
    auth.tokenSource.file.path = "/etc/frp/token"

    transport.tls.enable = true
    transport.tls.certFile = "/etc/frp/client.crt"
    transport.tls.keyFile = "/etc/frp/client.key"
    transport.tls.trustedCaFile = "/etc/frp/ca.crt"
    transport.tls.serverName = "frps-gateway"
    transport.poolCount = 1

    [[proxies]]
    name = "lucky-pm-frontend"
    type = "tcp"
    localIP = "lucky-web.lucky.svc.cluster.local"
    localPort = 18444
    remotePort = 19080

    [[proxies]]
    name = "lucky-pm-backend"
    type = "tcp"
    localIP = "lucky-web.lucky.svc.cluster.local"
    localPort = 18445
    remotePort = 19081

    [[proxies]]
    name = "lucky-pms"
    type = "tcp"
    localIP = "lucky-web.lucky.svc.cluster.local"
    localPort = 18446
    remotePort = 19082

    [[proxies]]
    name = "lucky-sso"
    type = "tcp"
    localIP = "lucky-web.lucky.svc.cluster.local"
    localPort = 18447
    remotePort = 19083

    [[proxies]]
    name = "lucky-pms-api"
    type = "tcp"
    localIP = "lucky-web.lucky.svc.cluster.local"
    localPort = 18448
    remotePort = 19084

    [[proxies]]
    name = "litellm-inference-api"
    type = "tcp"
    localIP = "litellm-public-api.litellm.svc.cluster.local"
    localPort = 8080
    remotePort = 19085

    [[proxies]]
    name = "pdep"
    type = "tcp"
    localIP = "pdep-nginx.pdep.svc.cluster.local"
    localPort = 80
    remotePort = 19079
