apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lucky-config
  namespace: lucky
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-home-retain
  resources:
    requests:
      storage: 1Gi
